GET http://localhost:5000/api/user/1/


GET http://localhost:5000/api/users


POST http://localhost:5000/api/plans HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJtcmM1NjIyQG91dGxvb2suY29tIiwiaWF0IjoxNTMxMDcwMzYwLCJleHAiOjE1MzEwNzIxNjB9.JxEnyrYiMDSQGGdo04aPQEjBkNWXNLA_-Ci8VD4PiS0

{
	"name":"Youtube Music",
	"payment": 150.00,
	"card_number":"123456789011",
	"participants_number": 6,
	"status": true,
	"participants_pay":"25",
	"type_pay": 1,
	"owner_id": 6
}