"""empty message

Revision ID: ac50c790b29c
Revises: 
Create Date: 2018-04-12 19:59:13.511917

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ac50c790b29c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make_payments', sa.Boolean(), nullable=True),
    sa.Column('number_pays', sa.Integer(), nullable=True),
    sa.Column('payment_to', sa.DateTime(), nullable=True),
    sa.Column('participant_id', sa.Integer(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pays')
    op.add_column('plans', sa.Column('payment', sa.Float(), nullable=True))
    op.drop_column('plans', 'pay')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('pay', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('plans', 'payment')
    op.create_table('pays',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('make_pays', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('number_pays', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pay_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('participant_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('plan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['users.id'], name='pays_participant_id_fkey'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], name='pays_plan_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='pays_pkey')
    )
    op.drop_table('payments')
    # ### end Alembic commands ###
