"""empty message

Revision ID: 4254db03f7d4
Revises: 9ad57b7289e4
Create Date: 2018-07-07 22:45:20.959880

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4254db03f7d4'
down_revision = '9ad57b7289e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'created_at')
    op.drop_column('users', 'name')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('name', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('last_name', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'password',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
