"""empty message

Revision ID: 9ad57b7289e4
Revises: ee92a560bdb2
Create Date: 2018-07-07 16:43:54.380305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ad57b7289e4'
down_revision = 'ee92a560bdb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('payment_month', sa.Text(), nullable=True))
    op.drop_column('payments', 'make_payments')
    op.drop_column('payments', 'payment_to')
    op.drop_column('payments', 'number_pays')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('number_pays', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('payment_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('payments', sa.Column('make_payments', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('payments', 'payment_month')
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###
